### ISSUE TITLE
Umbraco ID login loop when using UmbracoAuthorizedApiController

### ISSUE THREAD

**Issue by NISPico** [umbraco/Umbraco.Cloud.Issues#672]
### Issue description

I have an issue with a login loop when using a UmbracoAuthorizedApiController with Umbraco ID.
My setup is:

A UmbracoAuthorizedApiController with a method that requires you to be logged into to the backoffice to access `[Authorize(Policy = AuthorizationPolicies.BackOfficeAccess)]`

### Example for controller
```
public class BackofficeController : UmbracoAuthorizedApiController
{
    [Authorize(Policy = AuthorizationPolicies.BackOfficeAccess)]
    public string GetFile(string? fileName)
    {
           ...
           return File(stream, blobClient.GetProperties().Value.ContentType);
    }
}
```

### Usecase:

- A user fills out a form with file upload
- The file is placed in a blob storage
- A backoffice user gets a mail with the form data including a link to the file
- The backoffice user clicks the link in the mail with the file, to download/preview it
- Secure method in UmbracoAuthorizedApiController to download the file is triggered, and the user is prompted to login
- This is where the issue starts, when trying to log in with umbraco ID the login popup just opens another login page and so on..

###  What i have tested:
 That this works outside of cloud on a fresh CMS v12 install.
 If you are not using Umbraco ID and just a standard Username & Password login it works as intended.
 
 ### Version
 Umbraco.CMS 12.0.1
 Umbraco.Cloud.Identity.CMS 12.0.8

**Comment by sajumb** [comment]
Hi,
Thanks for the nice issue description. We will into the issue and see what can be done about it.

**Comment by mclausen** [comment]
Hi @NISPico,
Thank you for providing an excellent sample 👌

On Tuesday 2023-10-10, we released a patch upgrade for Umbraco ID (12.0.11) and Public Access (12.0.3). With that, we had a chance to revisit the redirect logic that caries the users back and forth, from the origin URL to Umbraco ID + Sign-in, and then back to to origin URL (now authenticated). I believe that this should solve the issue that you are seeing.

If you wouldn't mind, I would love for you to try your workflow again on the newest patch, and meanwhile, we'll try and reproduce it locally in our upcoming sprint starting Monday the 23rd.

**Comment by NISPico** [comment]
I tried updating the newest patch and i still face the issue.

Nikolaj Skovmose
Backend developer, PicoPublish
[cid:82279506-e61c-4a2f-a39a-a91a9b7608e0]
+45 20 10 03 51


________________________________
Fra: Martin Humlund Clausen ***@***.***>
Sendt: 12. oktober 2023 13:26
Til: umbraco/Umbraco.Cloud.Issues ***@***.***>
Cc: Nikolaj Skovmose ***@***.***>; Mention ***@***.***>
Emne: Re: [umbraco/Umbraco.Cloud.Issues] Umbraco ID login loop when using UmbracoAuthorizedApiController (Issue #672)


Hi @NISPico<https://github.com/NISPico>,
Thank you for providing an excellent sample 👌

On Tuesday 2023-10-10, we released a patch upgrade for Umbraco ID (12.0.11) and Public Access (12.0.3). With that, we had a chance to revisit the redirect logic that caries the users back and forth, from the origin URL to Umbraco ID + Sign-in, and then back to to origin URL (now authenticated). I believe that this should solve the issue that you are seeing.

If you wouldn't mind, I would love for you to try your workflow again on the newest patch, and meanwhile, we'll try and reproduce it locally in our upcoming sprint starting Monday the 23rd.

**Comment by mclausen** [comment]
Hi @NISPico 
We've reproduced the issue as well, and we are actively implementing a patch. We expect a new patch to be released next week, and subsequently Cloud Websites for +9 to be auto-upgraded on Tuesday 14 November.

**Comment by mikkelhm** [comment]
Hey @NISPico

We have added a -beta version of Umbraco.Cloud.Identity.Cms, if you would like to try it out - the only change should be the handling of redirects from an `UmbracoAuthorizedApiController` .

The version you would want to go to is `12.0.22-beta` (https://www.nuget.org/packages/Umbraco.Cloud.Identity.Cms/12.0.22-beta)- If you are not fond of testing out beta packages, then no worries - once the code has been reviewed and merged, cloud projects will be upgraded to the final version automatically.

**Comment by sajumb** [comment]
We recently observed that the introduction of Umbraco.Cloud.Identity.Cms, which includes support for UmbracoAuthorizedApiController, inadvertently impacted cloud projects that integrate external login providers such as Active Directory or Google Suite. This issue led to unforeseen complications in these environments. As a result, we have decided to revert to the previous version of the system that does not include this feature. We are actively working on resolving the issues and will provide updates as soon as improvements are made and the feature is ready for re-release.

**Comment by jemayn** [comment]
Thank you for reporting this. We're closing this issue as part of a cleanup of older items on the tracker. If you're still experiencing this problem on a current version of Umbraco Cloud, please open a new issue and we'll investigate.
